language: go
services:
- docker
os: linux
sudo: required
dist: trusty
go:
- 1.11.x
env:
  global:
  - CHANGE_MINIKUBE_NONE_USER=true
  - TAG=${TRAVIS_TAG:=${TRAVIS_COMMIT}}
  - GH_URL=https://amadeusitgroup.github.io/workflow-controller
  - IMAGE_NAME=traviscontroller
  matrix:
  - CLUSTER=openshift
  - CLUSTER=kubernetes
go_import_path: github.com/amadeusitgroup/workflow-controller
before_install:
# install nsenter for helm and port forwarding
- sudo apt-get -qq update
- sudo apt-get install -y socat
- docker run --rm jpetazzo/nsenter cat /nsenter > /tmp/nsenter && chmod +x /tmp/nsenter
- sudo cp /tmp/nsenter /usr/local/bin
- curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
script:
- ./hack/run-test-ci.sh
stages:
- name: docker-push
  if: type NOT IN (pull_request)
- name: release
  if: tag IS present
jobs:
  include:
  - stage: docker-push
    name: docker-build
    deploy:
    - provider: script
      script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && cd $TRAVIS_BUILD_DIR && make TAG=$TRAVIS_BRANCH push
      on:
        branch: master
  - stage: release
    script:
      - docker login -u "$DOCKER_USERNAME" p "$DOCKER_PASSWORD"
      - curl -sL https://git.io/goreleaser | bash
    deploy:
    - provider: releases
      api_key:
        secure: $GITHUB_TOKEN
      skip_cleanup: true
      file:
      - docs/workflow-controller-$TAG.tgz
      on:
        tags: true
        branches:
          only:
          - master
          - /^v\d+(\.\d+)+$/
after_success:
- bash <(curl -s https://codecov.io/bash) -f $TRAVIS_BUILD_DIR/.cover/cover.out
