language: go
os: linux
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
go:
  - 1.8.3
go_import_path: github.com/sdminonne/workflow-controller
install:
  - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
  - mkdir -p .bin; mv ./kubectl .bin/kubectl && chmod +x .bin/kubectl
  - export PATH="$TRAVIS_BUILD_DIR/.bin:$PATH"
  - wget https://cdn.rawgit.com/Mirantis/kubeadm-dind-cluster/master/fixed/dind-cluster-v1.7.sh && chmod +x dind-cluster-v1.7.sh && ./dind-cluster-v1.7.sh up
  - export PATH="$HOME/.kubeadm-dind-cluster:$PATH"
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  - kubectl -n kube-system create sa tiller
  - kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
  - helm init --service-account tiller

script:
  - make container_test
  - make container
  - helm install --version latest -n end2end-test charts/workflow-controller --set image.pullPolicy=IfNotPresent
  - while [ $(kubectl get pod --selector=app=workflow-controller --all-namespaces | grep 'workflow-controller' | awk '{print $4}') != "Running" ]; do echo "$(kubectl get pod --selector=app=workflow-controller --all-namespaces)"; sleep 5; done
  - cd ./test/e2e && go test -c && ./e2e.test --kubeconfig=$HOME/.kube/config --ginkgo.slowSpecThreshold 30
  - helm delete end2end-test
after_success:
  - bash <(curl -s https://codecov.io/bash)
