kind: Workflow
apiVersion: "example.com/v1"
metadata:
  name: hello-workflow
spec:
  metadata:
    name: hello-workflow
  selector:
    matchLabels:
      workflow: hello
  steps:
  - name: one
    jobTemplate:
      spec:
        template:
          metadata:
            name: step_one
            labels:
              workflow: step_one
          spec:
            restartPolicy: Never
            dnsPolicy: Default
            containers:
              - name: step-one-wait-and-exit
                image: gcr.io/google_containers/busybox
                command: ["sh", "-c", "echo Starting on: $(date); sleep 5; echo Goodbye cruel world at: $(date)"]
