apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: workflow-controller-deployment
spec:
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      serviceAccount: workflow-controller
      containers:
      - name: workflow-controller
        image: sdminonne/workflow-controller:0.0
        args: ["--resource-versions=v1", "--domain=example.com", "--name=workflow"]
      