// Generated file, do not modify manually!

// This file was automatically generated by lister-gen

package v1

// WorkflowListerExpansion allows custom methods to be added to
// WorkflowLister.
type WorkflowListerExpansion interface{}

// WorkflowNamespaceListerExpansion allows custom methods to be added to
// WorkflowNamespaceLister.
type WorkflowNamespaceListerExpansion interface{}
