apiVersion: "workflow.k8s.io/v1"
kind: DaemonSetJob
metadata:
  name: hello-dsj
spec:
  metadata:
    name: hello-dsj
  selector:
    matchLabels:
      workflow: hello
  jobTemplate:
    spec:
      template:
        metadata:
          name: job1
        spec:
          restartPolicy: Never
          dnsPolicy: Default
          containers:
            - name: step-one-wait-and-exit
              image: gcr.io/google-containers/busybox
              command: ["sh", "-c", "echo Starting on: $(date); sleep 5; echo Goodbye cruel world at: $(date)"]
