apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: workflow-controller
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      serviceAccount: workflow-controller
      containers:
      - name: workflow-controller
        image: workflowctrl/workflow-controller:latest
        imagePullPolicy: Always
        args: ["--v=2"]
        livenessProbe:
          httpGet:
            path: /live
            port: 8086
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8086
          periodSeconds: 5
