# workflow-controller role
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: workflow-controller
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources:
  - customresourcedefinitions
  verbs: ["*"]
- apiGroups: ["workflow.k8s.io"]
  resources:
  - workflows
  - cronworkflows
  - daemonsetjobs
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["list"]

---
# Cluster role binding
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: workflow-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workflow-controller
subjects:
- kind: ServiceAccount
  name: workflow-controller
  namespace: kube-system

---
# Service Account
kind: ServiceAccount
apiVersion: v1
metadata:
  name: workflow-controller
  namespace: kube-system
