apiVersion: v1
kind: List
items:
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    name: workflow-controller
  rules:
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - "*"
  - apiGroups:
    - dag.example.com
    resources:
    - workflows
    verbs:
    - "*"
  - apiGroups:
    - batch
    resources:
    - jobs
    verbs: ["*"]
  - apiGroups: [""]
    resources:
    - namespaces
    verbs: ["list"]
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: workflow-controller
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: workflow-controller
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: workflow-controller
  subjects:
  - kind: ServiceAccount
    name: workflow-controller
    namespace: default
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: workflow-controller
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: workflow-controller
      spec:
        serviceAccount: workflow-controller
        containers:
        - name: workflow-controller
          image: sdminonne/workflow-controller:latest
          imagePullPolicy: IfNotPresent
          args: ["--v=2"]
