// Generated file, do not modify manually!

// This file was automatically generated by informer-gen

package v1

import (
	internalinterfaces "github.com/sdminonne/workflow-controller/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Workflows returns a WorkflowInformer.
	Workflows() WorkflowInformer
}

type version struct {
	internalinterfaces.SharedInformerFactory
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory) Interface {
	return &version{f}
}

// Workflows returns a WorkflowInformer.
func (v *version) Workflows() WorkflowInformer {
	return &workflowInformer{factory: v.SharedInformerFactory}
}
