apiVersion: v1
description: A simple Kubernetes workflow controller
name: workflow-controller
version: 0.0.0
keywords:
- kubernetes
- workflow
home: https://github.com/amadeusitgroup/workflow-controller
sources:
- https://github.com/amadeusitgroup/workflow-controller
